version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: agri
      DB_USERNAME: agri
      DB_PASSWORD: agri
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: agri
      MYSQL_USER: agri
      MYSQL_PASSWORD: agri
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33060:3306"

volumes:
  dbdata: {}


