FROM dunglas/frankenphp:1-php8.3

WORKDIR /app

COPY . /app

RUN install-php-extensions pcntl pdo_mysql gd zip intl opcache

RUN cp .env.example .env \
    && composer install --no-dev --optimize-autoloader --no-interaction \
    && php artisan key:generate \
    && php artisan config:cache \
    && php artisan route:cache \
    && php artisan view:cache

EXPOSE 8000

CMD ["php", "artisan", "octane:start", "--server=frankenphp", "--host=0.0.0.0", "--port=8000"]


